#!/usr/bin/bash

## Check if running as sudo/root ##
if [ $EUID != 0 ] ; then
  echo "Must sudo or be root.  Terminating..." >&2
  exit 1
fi

autoprepare_format() {
  local PART_ROOT=$1
  local LOG=$2

  # we are forcing it, since parted seems to create an ext2 file system automatically
  mkfs.btrfs -L pacnas_root -f ${PART_ROOT} >>/tmp/debug.log #${LOG}

  mkdir -p /mnt/pacnas_root >${LOG}
  # make sure, this is really an ssd, let the user choose?
  mount -o defaults,noatime ${PART_ROOT} /mnt/pacnas_root >>/tmp/debug.log #${LOG}
  cd /mnt/pacnas_root

  # enable snapshot functionality
  mkdir __snapshot
  btrfs subvolume create __active && cd __active >>/tmp/debug.log #${LOG}
  btrfs subvolume create home >>/tmp/debug.log #${LOG}
  btrfs subvolume create var >>/tmp/debug.log #${LOG}
  btrfs subvolume create usr >>/tmp/debug.log #${LOG}

  chmod 755  ../\__active home var usr

  mkdir /mnt/pacnas_active >>/tmp/debug.log #
  mount -o defaults,noatime,subvol=__active ${PART_ROOT} /mnt/pacnas_active
  cd /mnt/pacnas_active
}

# vim: set ts=2 sw=2 et: