#!/usr/bin/bash

## Check if running as sudo/root ##
if [ $EUID != 0 ] ; then
  echo "Must sudo or be root.  Terminating..." >&2
  exit 1
fi

autoprepare_format() {
  local PART_ROOT=$1
  local ROTATIONAL=$2
  local LOG=$3

  # we are forcing it, since parted seems to create an ext2 file system automatically
  mkfs.btrfs -L pacnas_root -f ${PART_ROOT} >>/tmp/debug.log #${LOG}

  mkdir -p /mnt/pacnas_root >${LOG}
  # make sure, this is really an ssd
  MOUNT_OPTIONS="defaults,noatime,compress=lzo"
  if [ "$ROTATIONAL" = "0" ]; then
    MOUNT_OPTIONS=$MOUNT_OPTIONS,ssd
  fi

  mount -o ${MOUNT_OPTIONS} ${PART_ROOT} /mnt/pacnas_root >>/tmp/debug.log #${LOG}
  cd /mnt/pacnas_root

  # enable snapshot functionality
  btrfs subvolume create __snapshot/__active && cd __active >>/tmp/debug.log #${LOG}
  btrfs subvolume create __snapshot/home >>/tmp/debug.log #${LOG}
#  btrfs subvolume create __snapshot/var >>/tmp/debug.log #${LOG}

  chmod 755  ../\__active home

  for subvolid in $(btrfs subvolume list '/mnt/pacnas_root/__snapshot' | /usr/bin/awk '/__active/ {print $2}') # scan
  do
    btrfs subvolume set-default $subvolid
    # there should be just one ;-)
    break;
  done

  mkdir /mnt/pacnas_active >>/tmp/debug.log #
  umount /mnt/pacnas_root

  # need to provide info, if the disc is an ssd, we are booting default subvolume here (__active)
  mount -o ${MOUNT_OPTIONS} ${PART_ROOT} /mnt/pacnas_active

  cd /mnt/pacnas_active
  mkdir -p var/lib/btrfs
  # mount all subvolumes into /var/lib/btrfs to be able to create further subvolumes and snapshots
  mount -o ${MOUNT_OPTIONS},subvolid=0 ${PART_ROOT} /mnt/pacnas_active/var/lib/btrfs

  # optional
  mkdir /mnt/pacnas_active/var/lib/btrfs/emtpy
  mount --bind /mnt/pacnas_active/var/lib/btrfs/empty /mnt/pacnas_active/var/lib/btrfs/__active
}

# vim: set ts=2 sw=2 et: