#!/bin/bash
# written by Alex Filgueira <faidoc@gmail.com>
# Adopted for pacNAS by Markus M. May <triplem@pacnas.org>
TEXTDOMAIN=pacnas_installer

ANSWER="/tmp/.kb"
TITLE=$"pacNAS Keyboard Setting"

if [[ "${1}" = "--setup" ]]; then
    EXIT=$"Return to Main Menu"
else
    EXIT=$"Exit"
fi

abort()
{
    DIALOG --yesno $"Abort Keyboard Setting?" 6 42 || return 0
    [[ -e /tmp/.kb ]] && rm -f /tmp/.kb
    [[ -e /tmp/.keymap ]] && rm -f /tmp/.keymap
    [[ -e /tmp/.kb-running ]] && rm /tmp/.kb-running

    clear
    exit 1
}

# DIALOG()
# an el-cheapo dialog wrapper
#
# parameters: see dialog(1)
# returns: whatever dialog did
DIALOG() {
    dialog --backtitle "${TITLE}" --aspect 15 "$@"
    return $?
}

error_kbset()
{
    DIALOG --msgbox $"An error occured, your current language was not selected." 0 0
}

dokeymaps() {
    KBDDIR="/usr/share/kbd/keymaps"

    # "Scanning for locales..."
    KEYMAPS=
    for i in $(find $KBDDIR -name "*.gz" | sort); do
        KEYMAPS="$KEYMAPS ${i##$KBDDIR/} -"
    done

    CANCEL=""
    DIALOG --menu $"Select A Keymap" 22 60 16 ${KEYMAPS} 2>${ANSWER} || CANCEL="1"
    if [[ "${CANCEL}" = "1" ]]; then
        S_NEXTITEM="1"
        return 1
    fi
    keymap=$(cat ${ANSWER})
    echo ${keymap} > /tmp/.keymap
    if [[ "${keymap}" ]]; then
        loadkeys $KBDDIR/${keymap}
    fi
S_NEXTITEM=2
}

mainmenu() {
    if [[ -n "${S_NEXTITEM}" ]]; then
        DEFAULT="--default-item ${S_NEXTITEM}"
    else
        DEFAULT=""
    fi
    DIALOG ${DEFAULT} --backtitle "${TITLE}" --title " MAIN MENU " \
                --menu $"Use the UP and DOWN arrows to navigate menus.\nUse TAB to switch between buttons and ENTER to select." 17 58 13 \
        "1" $"Set Keymap" \
        "2" "${EXIT}" 2>${ANSWER}
    case $(cat ${ANSWER}) in
        "1")
            dokeymaps
            ;;
        "2")
            [[ -e /tmp/.kb-running ]] && rm /tmp/.kb-running
            clear
            exit 0 ;;
        *)
            abort ;;
    esac
}

: >/tmp/.keymap
: >/tmp/.kb



if [[ -e /tmp/.kb-running ]]; then
    echo "kb already runs on a different console!"
    echo "Please remove /tmp/.kb-running first to continue!"
    exit 1
fi
: >/tmp/.kb-running

while true; do
    mainmenu
done

clear
exit 0

# vim: set ts=4 sw=4 et: